### ISSUE TITLE
Feature: Dashboard

### ISSUE THREAD

**Issue by mrkgnt** [axell1756/crypto-dashboard#3]
# Epic Title

Feature: Dashboard

## Epic Description

This Feature will add crypto currency dashboard that is separated into 2 sections - coin list and selected coin detail.

### Left side of the dashboard
![image](https://user-images.githubusercontent.com/8956158/108094158-6baec600-7076-11eb-8fe5-2b0af8acdd3d.png)
[Source](https://www.coindesk.com/coindesk20)

Right side of the dashboard should have Top 20 most performing coins overall. By selecting any of the coin, insight information should be displayed to the right of the table.

### Right side of the dashboard
![image](https://user-images.githubusercontent.com/8956158/108094714-00b1bf00-7077-11eb-962f-b39589c5295d.png)
[Source](https://www.coindesk.com/price/dash)
![image](https://user-images.githubusercontent.com/8956158/108095359-ae24d280-7077-11eb-9a39-2498838f2a67.png)
[Source](https://www.coindesk.com/price/dash)

Right side of the dashboard will display key details and information about current trends, volatility, growth etc. about selected coin in the left table.

<hr>

Feature is meant to let users easily navigate cryptocurrencies and, upon selection, get all the necessary information about coin of interest.

## List of Tasks (Complete in order)

- [x] [Task 1: Create Dashboard Coin Table](https://github.com/axell1756/crypto-dashboard/issues/4)
- [ ] [Task 2: Dashboard Coin Details](https://github.com/axell1756/crypto-dashboard/issues/5)
- [ ] [Task 3: Coin historical graph](https://github.com/axell1756/crypto-dashboard/issues/10)
- [ ] [Task 3: Coin related news](https://github.com/axell1756/crypto-dashboard/issues/9)
